version: "3.4"

services:
  pg:
    image: postgres:14-alpine
    ports:
      - 55432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: <database name>
    volumes:
      - pg-data:/var/lib/postgresql/data:delegated

volumes:
  pg-data:
